### PR TITLE
Plain HTTP support

### PR DESCRIPTION
**Pull request by oklona**
Added the necessary changes to get support for plain HTTP, based on suggestion from @mhdawson

### CODE REVIEW

**Comment by mhdawson** [comment]
Looks good but I'd like to leave the default as with ssl, can you change the value in the configuration file to "false".  It should also be added to the doc in the README.md.

**Comment by oklona** [comment]
Of course! Very good (and valid) point.

**Comment by oklona** [comment]
I made the changes now. Is the PR automatically updated, or do I need to do anything else?

**Comment by mhdawson** [comment]
Looks good.  I'll try to validate and land this weekend.  Thanks for helping to improve the bridge:)

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
